packages:
  - artifacts/*
  - lib/*
  - services/*

autoInstallPeers: false

catalog:
  '@types/node': ^25.3.3
  drizzle-orm: ^0.45.1
  tsx: ^4.21.0
  zod: 3.25.76

onlyBuiltDependencies:
  - esbuild

overrides:
  esbuild: 0.27.3
